vagas_index:
    path:     /
    defaults: { _controller: "MyAppAquitemBicoBundle:Vagas:index" }
    methods:  GET

vagas_show:
    path:     /{id}/show
    defaults: { _controller: "MyAppAquitemBicoBundle:Vagas:show" }
    methods:  GET

vagas_new:
    path:     /new
    defaults: { _controller: "MyAppAquitemBicoBundle:Vagas:new" }
    methods:  [GET, POST]

vagas_edit:
    path:     /{id}/edit
    defaults: { _controller: "MyAppAquitemBicoBundle:Vagas:edit" }
    methods:  [GET, POST]

vagas_delete:
    path:     /{id}/delete
    defaults: { _controller: "MyAppAquitemBicoBundle:Vagas:delete" }
    methods:  DELETE
